name: Cypress Tests I

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line

jobs: 
  cypress-electon-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
        
      - name: Install dependencies
        run: yarn install
        
      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
