name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*
        
jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
        
      - name: Cypress run
        uses: cypress-io/github-actions@v5.0.8
        with:
          install command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 754df4c3-07a1-4111-b0f5-dfcdb8774fa1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
